runtime: python312  # 根據您的 Python 版本調整，例如 python312
service: postflask  # 定義服務名稱為 post_flask
instance_class: F1  # 選擇實例類型，F1 是免費層級

handlers:
- url: /.*
  script: auto

# 指定主應用程式檔案
entrypoint: gunicorn -b :$PORT main:app

# 確保依賴在部署時安裝
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10